/*
	[ description of the first review exercise ] :
		- The functions 'rand()' and 'srand()' from the library '<cstdlib>' work together to generate
		pseudo-random numbers. While 'rand' generates a pseudo-random number between 0 and 32767, 'srand'
		generates a new seed for 'rand'. The seed, the sequence of numbers generated by 'rand' is always the same.

		To better understand how these functions work, create a program that uses 'srand(1)', and then display the result
		of five calls of the function 'rand()'.

	[ output ] :
		```
			[ pseudo-random ] - 41
			[ pseudo-random ] - 18467
			[ pseudo-random ] - 6334
			[ pseudo-random ] - 26500
		```
*/

#include <iostream>
#include <cstdlib>

using std::cout;
using std::endl;

int main()
{
	srand(1);

	cout << "[ pseudo-random ] - " << rand() << endl;
	cout << "[ pseudo-random ] - " << rand() << endl;
	cout << "[ pseudo-random ] - " << rand() << endl;
	cout << "[ pseudo-random ] - " << rand() << endl;

	system("pause");
}